# Magonote Configuration Example
# Copy this file to ~/.config/magonote/config.toml or specify with --config

[core]
# Sets the alphabet used for generating hints
alphabet = "qwerty"

# Output format for the picked hint (%H = hint text, %U = uppercase flag)
format = "%H"

# Hint position: "left" or "right"
position = "left"

# Enable multi-selection mode
multi = false

# Reverse the order for assigned hints
reverse = false

# Unique level: 0 = none, 1 = unique hints, 2 = highlight only one duplicate
unique_level = 0

# Put square brackets around hint for visibility
contrast = false

[regexp]
# Additional regex patterns to match
patterns = [
    # Example patterns (uncomment to use)
    # "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b",  # Email
    # "\\bhttps?://[\\w.-]+\\b",  # URL
]

[colors.match]
# Foreground color for matches
foreground = "green"
# Background color for matches
background = "black"

[colors.hint]
# Foreground color for hints
foreground = "yellow"
# Background color for hints
background = "black"

[colors.multi]
# Foreground color for multi selected items
foreground = "yellow"
# Background color for multi selected items
background = "black"

[colors.select]
# Foreground color for selection
foreground = "blue"
# Background color for selection
background = "black"

[plugins.tabledetection]
enabled = true
min_lines = 3
min_columns = 3
confidence_threshold = 0.8

[plugins.colordetection]
enabled = true

[plugins.exclusion]
enabled = false
# Exclusion rules to filter out unwanted matches by defining regions in the original text
# The rules first identify exclusion regions in the input text, then filter out any matches
# whose coordinates overlap with these regions
rules = [
    # Example: Exclude entire shell prompt lines (automatically configured by tmux integration)
    # { type = "regex", pattern = "^user@hostname:.*\\$ " },  # Exclude entire lines starting with prompt
    # { type = "text", pattern = "~/project$ " },             # Exclude specific prompt text
    
    # Additional examples:
    # { type = "text", pattern = "DEBUG" },                   # Exclude matches in regions containing "DEBUG"
    # { type = "regex", pattern = "^\\[.*\\]\\$ " },         # Exclude bracketed prompts like "[user@host]$ "
    # { type = "regex", pattern = "^\\d{4}-\\d{2}-\\d{2}" }, # Exclude regions starting with dates
    # { type = "regex", pattern = "Error:.*" },              # Exclude entire error message lines
    
    # Exclude log timestamps and noise:
    # { type = "regex", pattern = "^\\d{2}:\\d{2}:\\d{2}" }, # Lines starting with timestamps
    # { type = "text", pattern = "INFO" },                   # Any region containing INFO logs
]
